---
# tasks file for apache2
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_state }}"
    enabled: true

- include_tasks: vhost.yml
  when: apache_vhosts is defined
