---
# vars file for php
php_packages:
  - php{{ php_version_debian }}
  - php{{ php_version_debian }}-mysql
  - php{{ php_version_debian }}-cli
  - php{{ php_version_debian }}-dev
  - php{{ php_version_debian }}-fpm
  - php{{ php_version_debian }}-zip
  - libpcre3-dev
  - libapache2-mod-php
  - php{{ php_version_debian }}-gd
  - php{{ php_version_debian }}-curl
  - php{{ php_version_debian }}-imap
  - php{{ php_version_debian }}-json
  - php{{ php_version_debian }}-xml
  - php{{ php_version_debian }}-mbstring
  - php-ldap
  - php-bcmath

php_conf_paths: /etc/php/{{ php_version_debian }}/fpm/php.ini
php_extension_conf_paths:
  - /etc/php/{{ php_version_debian }}/fpm/conf.d
  - /etc/php/{{ php_version_debian }}/apache2/conf.d
  - /etc/php/{{ php_version_debian }}/cli/conf.d

php_fpm_daemon: php{{ php_version_debian }}-fpm
php_fpm_conf_path: "/etc/php/{{ php_version_debian }}/fpm"
php_fpm_pool_conf_path: "{{ php_fpm_conf_path }}/pool.d/www.conf"
php_fpm_pool_user: www-data
php_fpm_pool_group: www-data
