---
# vars file for apache2
apache_service: apache2
apache_daemon: apache2
apache_daemon_path: /usr/sbin/
apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2
APACHE_LOG_DIR: /var/log/apache2
__apache_packages:
  - apache2
  - apache2-utils
  - libapache2-mod-fastcgi
